# Generated by Django 5.2.5 on 2026-09-25 15:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("completed", "Complété"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="nom du contact",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="e-mail du contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="téléphone du contact",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="systèmes sélectionnés"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", verbose_name="détails de la demande"
                    ),
                ),
                (
                    "rooms",
                    models.PositiveIntegerField(default=0, verbose_name="pièces"),
                ),
                (
                    "entries",
                    models.PositiveIntegerField(default=0, verbose_name="entrées"),
                ),
                (
                    "windows",
                    models.PositiveIntegerField(default=0, verbose_name="fenêtres"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "total_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="estimation",
                    ),
                ),
            ],
            options={
                "verbose_name": "devis",
                "verbose_name_plural": "devis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="désignation",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="total ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de devis",
                "verbose_name_plural": "lignes de devis",
            },
        ),
    ]
