# Generated by Django 5.2.5 on 2025-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
