# Generated by Django 5.2.5 on 2026-09-25 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quotes.quote",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "-created_at"], name="quotes_quot_status_86add0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteitem",
            constraint=models.UniqueConstraint(
                fields=("quote", "product"), name="unique_product_per_quote"
            ),
        ),
    ]
