# Generated by Django 5.2.5 on 2025-10-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
