# Generated by Django 5.2.5 on 2025-10-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '0003_quoteitem_subtotal_alter_quote_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'verbose_name': 'Élément de Devis', 'verbose_name_plural': 'Éléments de Devis'},
        ),
        migrations.AddField(
            model_name='quote',
            name='entries',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'entrées"),
        ),
        migrations.AddField(
            model_name='quote',
            name='rooms',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de pièces'),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='windows',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fenêtres'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(help_text='Systèmes sélectionnés'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='message',
            field=models.TextField(default='', help_text='Détails: fonctionnalités, paramètres'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Complété')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
