"""
Django settings for backendapte project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = "users.User"

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-3#092o8nhfw0illb)@z4xp1@f-c!+z+&t+pysov6_v10)%ugo*'
DEBUG = True
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',  # ⚡ CORS
    'django_filters',

    # apps
    'apps.users',
    'apps.products',
    'apps.orders',
    'apps.quotes',
    'apps.cart',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ⚡ doit être en haut pour CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backendapte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendapte.wsgi.application'

# Sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Stocker en base
SESSION_COOKIE_AGE = 1209600  # 2 semaines
SESSION_SAVE_EVERY_REQUEST = True  # Sauvegarder à chaque requête

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media/Products files - Votre dossier "products" à la racine
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Dossier produits personnalisé
PRODUCTS_URL = '/products/'
PRODUCTS_ROOT = os.path.join(BASE_DIR, 'products')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "APTE API",
    "DESCRIPTION": "APTE",
    "VERSION": "1.0.0",
    "COMPONENT_SPLIT_REQUEST": False,
    "COMPONENT_SPLIT_PATCH": False,
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # autorise toutes les origines (dev)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # frontend React
]
# Pour autoriser l'envoi des cookies (si JWT via cookie)
# CORS_ALLOW_CREDENTIALS = True

# Wave Payment Configuration
WAVE_API_KEY = os.getenv('WAVE_API_KEY', '')
WAVE_SECRET_KEY = os.getenv('WAVE_SECRET_KEY', '')
WAVE_API_URL = 'https://api.wave.com/v1'  # URL de l'API Wave

# URLs pour callbacks
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'orders.log',
        },
    },
    'loggers': {
        'apps.orders': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}