# Generated by Django 5.2.5 on 2026-09-25 15:09

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="numéro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Émise"),
                            ("paid", "Payée"),
                            ("canceled", "Annulée"),
                        ],
                        default="issued",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="émise le"
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="échéance"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="réglée le"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "subtotal_excl_tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="total HT"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="taux de TVA",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="montant TVA"
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="frais de livraison",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="remise",
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="total TTC"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="client"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="téléphone"
                    ),
                ),
                (
                    "billing_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="adresse de facturation",
                    ),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ville"
                    ),
                ),
                (
                    "seller_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="émetteur"),
                ),
            ],
            options={
                "verbose_name": "facture",
                "verbose_name_plural": "factures",
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(unique=True, verbose_name="année"),
                ),
                (
                    "last_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="dernier numéro attribué"
                    ),
                ),
            ],
            options={
                "verbose_name": "séquence de facturation",
                "verbose_name_plural": "séquences de facturation",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("awaiting_payment", "Paiement en cours"),
                            ("paid", "Payée"),
                            ("shipped", "Expédiée"),
                            ("completed", "Terminée"),
                            ("canceled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Espèces à la livraison"), ("wave", "Wave")],
                        default="cash",
                        max_length=20,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Numéro Wave",
                        max_length=15,
                        verbose_name="numéro de paiement",
                    ),
                ),
                (
                    "delivery_name",
                    models.CharField(
                        max_length=255, verbose_name="nom du destinataire"
                    ),
                ),
                (
                    "delivery_phone",
                    models.CharField(
                        max_length=15, verbose_name="téléphone de livraison"
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(max_length=255, verbose_name="adresse"),
                ),
                (
                    "delivery_city",
                    models.CharField(max_length=100, verbose_name="ville"),
                ),
                (
                    "delivery_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="instructions"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "items_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="total des articles",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="frais de livraison",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="remise",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="total à payer",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="payée le"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="annulée le"
                    ),
                ),
            ],
            options={
                "verbose_name": "commande",
                "verbose_name_plural": "commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="désignation"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="prix unitaire"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="total ligne"
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de commande",
                "verbose_name_plural": "lignes de commande",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "provider",
                    models.CharField(
                        default="wave", max_length=32, verbose_name="prestataire"
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="référence prestataire",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="clé d'idempotence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("succeeded", "Réussi"),
                            ("failed", "Échoué"),
                            ("canceled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True, default="", verbose_name="URL de paiement"
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="motif d'échec",
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="réponse prestataire"
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="réglé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-created_at"],
            },
        ),
    ]
