# Generated by Django 5.2.6 on 2025-10-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces à la livraison'), ('wave', 'Wave')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro Wave pour le paiement', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wave_transaction_id',
            field=models.CharField(blank=True, help_text='ID de transaction Wave', max_length=255, null=True),
        ),
    ]
